-- 021: Disparos separados da ALURE, com várias empresas, login próprio e um conjunto de proteções por número.
-- Idempotente: pode rodar mais de uma vez. Os dados atuais ficam na empresa ALURE (id 1) e no número atual (id 1).

-- Empresas
CREATE TABLE IF NOT EXISTS dsp_companies (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  slug       text NOT NULL UNIQUE,
  active     boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO dsp_companies (id, name, slug) VALUES (1, 'ALURE', 'alure') ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('dsp_companies', 'id'), GREATEST((SELECT max(id) FROM dsp_companies), 1));

-- Logins do painel de disparos (separados do login da ALURE)
CREATE TABLE IF NOT EXISTS dsp_users (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  company_id    bigint REFERENCES dsp_companies(id) ON DELETE CASCADE,
  email         text NOT NULL UNIQUE,
  name          text NOT NULL,
  password_hash text NOT NULL,
  role          text NOT NULL DEFAULT 'member' CHECK (role IN ('admin','member')),
  active        boolean NOT NULL DEFAULT true,
  last_login_at timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dsp_sessions (
  token_hash text PRIMARY KEY,
  user_id    bigint NOT NULL REFERENCES dsp_users(id) ON DELETE CASCADE,
  company_id bigint REFERENCES dsp_companies(id) ON DELETE SET NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS dsp_sessions_user_idx ON dsp_sessions (user_id);
CREATE INDEX IF NOT EXISTS dsp_sessions_expires_idx ON dsp_sessions (expires_at);

-- Números (instâncias da Evolution). name NULL = instância da variável EVOLUTION_INSTANCE.
CREATE TABLE IF NOT EXISTS dsp_instances (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES dsp_companies(id) ON DELETE CASCADE,
  name       text UNIQUE,
  label      text NOT NULL,
  phone      text,
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);
INSERT INTO dsp_instances (id, company_id, name, label) VALUES (1, 1, NULL, 'Número principal') ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('dsp_instances', 'id'), GREATEST((SELECT max(id) FROM dsp_instances), 1));
CREATE INDEX IF NOT EXISTS dsp_instances_company_idx ON dsp_instances (company_id) WHERE deleted_at IS NULL;

-- Proteções: uma linha por número (id = dsp_instances.id)
ALTER TABLE broadcast_settings DROP CONSTRAINT IF EXISTS broadcast_settings_id_check;
ALTER TABLE broadcast_settings ALTER COLUMN id DROP DEFAULT;
ALTER TABLE broadcast_settings ALTER COLUMN id TYPE bigint;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'broadcast_settings_instance_fk') THEN
    ALTER TABLE broadcast_settings ADD CONSTRAINT broadcast_settings_instance_fk
      FOREIGN KEY (id) REFERENCES dsp_instances(id) ON DELETE CASCADE;
  END IF;
END $$;

-- Campanhas: empresa + número que envia
ALTER TABLE broadcast_campaigns
  ADD COLUMN IF NOT EXISTS company_id  bigint REFERENCES dsp_companies(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS instance_id bigint REFERENCES dsp_instances(id) ON DELETE CASCADE;
UPDATE broadcast_campaigns SET company_id = 1 WHERE company_id IS NULL;
UPDATE broadcast_campaigns SET instance_id = 1 WHERE instance_id IS NULL;
ALTER TABLE broadcast_campaigns ALTER COLUMN company_id SET NOT NULL, ALTER COLUMN instance_id SET NOT NULL;
DROP INDEX IF EXISTS broadcast_one_running_idx;
CREATE UNIQUE INDEX IF NOT EXISTS broadcast_one_running_per_instance_idx ON broadcast_campaigns (instance_id) WHERE status = 'running';
CREATE INDEX IF NOT EXISTS broadcast_campaigns_company_idx ON broadcast_campaigns (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS broadcast_campaigns_instance_idx ON broadcast_campaigns (instance_id, status);

-- Contatos: únicos por empresa (o mesmo número pode estar na Simple e na Phoenix)
ALTER TABLE broadcast_contacts
  ADD COLUMN IF NOT EXISTS company_id bigint REFERENCES dsp_companies(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS vars       jsonb NOT NULL DEFAULT '{}';
UPDATE broadcast_contacts SET company_id = 1 WHERE company_id IS NULL;
ALTER TABLE broadcast_contacts ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE broadcast_contacts DROP CONSTRAINT IF EXISTS broadcast_contacts_phone_key;
CREATE UNIQUE INDEX IF NOT EXISTS broadcast_contacts_company_phone_idx ON broadcast_contacts (company_id, phone);
CREATE INDEX IF NOT EXISTS broadcast_contacts_company_created_idx ON broadcast_contacts (company_id, created_at DESC);

-- Registro e incidentes por empresa/número
ALTER TABLE broadcast_events
  ADD COLUMN IF NOT EXISTS company_id  bigint REFERENCES dsp_companies(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS instance_id bigint REFERENCES dsp_instances(id) ON DELETE SET NULL;
UPDATE broadcast_events SET company_id = 1 WHERE company_id IS NULL;
UPDATE broadcast_events SET instance_id = 1 WHERE instance_id IS NULL AND campaign_id IS NULL;
CREATE INDEX IF NOT EXISTS broadcast_events_company_idx ON broadcast_events (company_id, created_at DESC);

ALTER TABLE broadcast_incidents ADD COLUMN IF NOT EXISTS instance_id bigint REFERENCES dsp_instances(id) ON DELETE CASCADE;
UPDATE broadcast_incidents SET instance_id = 1 WHERE instance_id IS NULL;
CREATE INDEX IF NOT EXISTS broadcast_incidents_instance_idx ON broadcast_incidents (instance_id, created_at DESC);

-- Prospecção por empresa
ALTER TABLE prospect_settings DROP CONSTRAINT IF EXISTS prospect_settings_id_check;
ALTER TABLE prospect_settings ALTER COLUMN id DROP DEFAULT;
ALTER TABLE prospect_settings ALTER COLUMN id TYPE bigint;
INSERT INTO prospect_settings (id) SELECT id FROM dsp_companies ON CONFLICT (id) DO NOTHING;

ALTER TABLE prospect_searches ADD COLUMN IF NOT EXISTS company_id bigint REFERENCES dsp_companies(id) ON DELETE CASCADE;
UPDATE prospect_searches SET company_id = 1 WHERE company_id IS NULL;
ALTER TABLE prospect_searches ALTER COLUMN company_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS prospect_searches_company_idx ON prospect_searches (company_id, id DESC);

ALTER TABLE prospects ADD COLUMN IF NOT EXISTS company_id bigint REFERENCES dsp_companies(id) ON DELETE CASCADE;
UPDATE prospects SET company_id = 1 WHERE company_id IS NULL;
ALTER TABLE prospects ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE prospects DROP CONSTRAINT IF EXISTS prospects_place_id_key;
CREATE UNIQUE INDEX IF NOT EXISTS prospects_company_place_idx ON prospects (company_id, place_id);
CREATE INDEX IF NOT EXISTS prospects_company_status_idx ON prospects (company_id, wa_status);

ALTER TABLE prospect_lists ADD COLUMN IF NOT EXISTS company_id bigint REFERENCES dsp_companies(id) ON DELETE CASCADE;
UPDATE prospect_lists SET company_id = 1 WHERE company_id IS NULL;
ALTER TABLE prospect_lists ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE prospect_lists DROP CONSTRAINT IF EXISTS prospect_lists_tag_key;
CREATE UNIQUE INDEX IF NOT EXISTS prospect_lists_company_tag_idx ON prospect_lists (company_id, tag);

-- Limpeza de sessões vencidas dos disparos
DELETE FROM dsp_sessions WHERE expires_at < now();

-- Conferência: tudo deve vir preenchido; sem_empresa deve ser 0
SELECT (SELECT count(*) FROM dsp_companies)  AS empresas,
       (SELECT count(*) FROM dsp_instances)  AS numeros,
       (SELECT count(*) FROM dsp_users)      AS logins,
       (SELECT count(*) FROM broadcast_settings) AS protecoes,
       (SELECT count(*) FROM broadcast_campaigns WHERE company_id IS NULL OR instance_id IS NULL)
     + (SELECT count(*) FROM broadcast_contacts WHERE company_id IS NULL)
     + (SELECT count(*) FROM prospects WHERE company_id IS NULL) AS sem_empresa;
